"""Application-wide constants."""

# Common AWS resource types for assessment filtering
AWS_RESOURCES = [
    "acm",
    "api_gateway",
    "alb",
    "athena",
    "cloudfront",
    "cloudwatch",
    "db_proxy",
    "dynamodb",
    "ecs",
    "eks",
    "elb",
    "iam",
    "internet_gateway",
    "kms",
    "lambda",
    "nat_gateway",
    "network_acl",
    "rds",
    "route53",
    "s3",
    "secretsmanager",
    "security_group",
    "ses",
    "sns",
    "sqs",
    "ssm_parameter",
    "vpc",
    "waf",
]
